# Generated by Django 3.1.4 on 2021-02-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='bpmn_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
