# Generated by Django 3.1.4 on 2021-02-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0002_auto_20210202_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='position',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
